#ifndef __TYPEDEF_H__
#define __TYPEDEF_H__

#define  UINT8  unsigned char   
#define  UINT16 unsigned int     
#define  UINT32 unsigned long       

#define  INT8   char            
#define  INT16  int             
#define  INT32  long            

#define  BOOL   UINT8           

#define  WPARAM  UINT32 
#define  LPARAM  UINT32 

#define  FP32    float
#define  FP64    double

#define  DATA           data
#define IDATA          idata
#define XDATA          xdata
#define PDATA          pdata

#define VOID        void
#define STATIC      static
#define EXTERN      extern
#define EXTERN_C	  extern
#define CONST       const
#define CODE        code
#define VOLATILE    volatile
#define VAR_T       UINT8

#define LOW         0UL
#define HIGH        1UL

#define ON          1UL
#define OFF         0UL

#define BYTE        UINT8
#define WORD        UINT16
#define DWORD       UINT32

#define UINT        UINT16




#endif
